Repository smartknob-ha/sdk, pull requests merged in 2024-05, with the labels that each got.

#31 feat: esp_err_t std::error_category implementation
  util/CMakeLists.txt
  util/component.mk
  util/include/esp_system_error.hpp
Labels: feature, firmware

#32 Feature/config provider
  config_provider/CMakeLists.txt
  config_provider/component.mk
  config_provider/include/ConfigProvider.hpp
Labels: firmware

#34 docs: update license to AGPL3
  LICENSE
Labels: documentation

#35 Feature/config provider additions
  config_provider/include/ConfigProvider.hpp
Labels: feature, firmware
