Repository smartknob-ha/sdk, pull requests merged in 2024-06, with the labels that each got.

#37 Error handling with `std::error_code` and `std::expected`
  manager/include/Component.hpp
  manager/src/Manager.cpp
  mock_component/include/MockComponent.hpp
  mock_component/src/MockComponent.cpp
  network_manager/CMakeLists.txt
  network_manager/src/NetworkManager.cpp
  test/test_manager.cpp
  util/CMakeLists.txt
  util/include/esp_system_error.hpp
  util/source/esp_system_error.cpp
  wifi/CMakeLists.txt
  wifi/src/AccessPoint.cpp
  wifi/src/Station.cpp
Labels: firmware

#38 enhancement: various manager improvements
  .clang-tidy
  config_provider/CMakeLists.txt
  manager/CMakeLists.txt
  manager/config
  manager/include/Component.hpp
  manager/include/Manager.hpp
  manager/src/Manager.cpp
  mock_component/include/MockComponent.hpp
  mock_component/src/MockComponent.cpp
  network_manager/include/NetworkManager.hpp
  network_manager/src/NetworkManager.cpp
  test/test_manager.cpp
  wifi/include/AccessPoint.hpp
  wifi/include/Station.hpp
  wifi/src/AccessPoint.cpp
  wifi/src/Station.cpp
Labels: enhancement

#41 feat: Component logLevel method
  manager/include/Component.hpp
Labels: feature, firmware

#42 refactor: Wifi station
  config_provider/include/ConfigProvider.hpp
  network_manager/config
  network_manager/include/NetworkManager.hpp
  network_manager/src/NetworkManager.cpp
  wifi/config
  wifi/include/AccessPoint.hpp
  wifi/include/Station.hpp
  wifi/src/AccessPoint.cpp
  wifi/src/Station.cpp
Labels: firmware
